FROM node:16

WORKDIR /app

# copy package.json and package-lock.json to install dependencies
COPY package*.json ./
RUN npm install

# copy source code to /app
COPY . .

EXPOSE 8080

CMD ["npm", "run", "serve"]